version: '3.3'

services:
  mongo:
    container_name: iot_mongo
    build:
      context: mongo
    ports:
      - 27018:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: iot_db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: iot
      ME_CONFIG_MONGODB_ADMINPASSWORD: iot

